name: Build Firmware (v1.5.2)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/supermileage/particle-v1.5.2
      credentials:
        username: ${{ secrets.CR_LOGIN }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          path: app

      - name: Build
        run: |
          make all PLATFORM=electron APPDIR=app TARGET_DIR=out
