name: Build Firmware
on: [push, pull_request]

jobs:
  build-urban:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 5

      - name: Diff Source and Libraries
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: urban lib

      - name: Build
        if: steps.changed.outputs.changed == 'true'
        run: |
          make urban

      - name: Upload
        if: steps.changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: urban-${{ github.sha }}
          path: output

  build-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 5

      - name: Diff Source and Libraries
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: proto lib

      - name: Build
        if: steps.changed.outputs.changed == 'true'
        run: |
          make proto

      - name: Upload
        if: steps.changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: proto-${{ github.sha }}
          path: output

  build-fc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 5

      - name: Diff Source and Libraries
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: fc lib

      - name: Build
        if: steps.changed.outputs.changed == 'true'
        run: |
          make fc

      - name: Upload
        if: steps.changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: fc-${{ github.sha }}
          path: output
